### ISSUE TITLE
Index contains " character

### ISSUE THREAD

**Issue by DAQEM** [Copystrike/AP-bottomdown#1]
The " character is on line:
https://github.com/Copystrike/AP-bottomdown/blob/master/src/pages/index.ejs#L33

This charcater can be seen on the index page on the bottom left of the pokemon image.

**Comment by Copystrike** [comment]
Thanks for reporting the issue, I have assigned someone to this issue that will resolve this issue in the future. For visualisation refrence of the issue, here is a screenshot of the charater on the live website:
![image](https://user-images.githubusercontent.com/26123873/226440779-aa80d830-14ea-4fe7-8d17-9433fe971c12.png)
